### ISSUE TITLE
[MS WINDOWS] Unable to run using newest version

### ISSUE THREAD

**Issue by themagicman412** [polastre/united#12]
I am unable to use the current December 9th 458b0ca commit due to exceptions no matter what I search. I was able to run builds prior to the utilization of Puppeteer and have installed Node.js as per the instructions in the ReadMe. I have attached examples of the output I receive when I try to run it. I appreciate any help you can provide!

![polastreerror](https://user-images.githubusercontent.com/16710413/36065473-82d7ba84-0e69-11e8-966a-c03189ac8e6f.png)

**Comment by polastre** [comment]
It looks like you're running on Windows. I don't have windows and have no intention of testing or supporting it. Your request does work on OS X and Linux. Perhaps someone that runs windows can help you out.

![image](https://user-images.githubusercontent.com/2539570/36066115-340c62de-0e59-11e8-8b3b-872f97f6622b.png)

**Comment by themagicman412** [comment]
Joe,

Thanks for the follow-up. I will fire up a Linux VM and run it there from
now on.

Kyle
