### ISSUE TITLE
Only one date is returned

### ISSUE THREAD

**Issue by offirh** [polastre/united#5]
I've just installed the  latest version of Node.js and the polastre/united on two PCs, work (Win10) and home (Win7).
on the work PC, that's behind corporate VPN, I've manually changed the NPM Proxy settings, and the connection seems successful. the home PC required no network changes.
running the same search string (or any other search) on the two computers, always returns different results:
`node united.js MUC SFO 4/1/2017 4/10/2017`
On the home PC I get one line per each date within my date range (green or red based on availability)
While on the work PC I always get just one result (in red) and it is not even the earliest date within my range, and then the loop seems to stop.
**Screenshot of Home PC results:**
![screenhunter_01 mar 06 09 54](https://cloud.githubusercontent.com/assets/26216650/23601496/6577f854-0254-11e7-9080-2020c1b363ef.jpg)

**Screenshot of Work PC results:**
![work](https://cloud.githubusercontent.com/assets/26216650/23601396/f0e7c3d4-0253-11e7-897d-228f26191986.jpg)

any ideas for troubleshooting?

**Comment by polastre** [comment]
can you check what version of `node` you're running on both computers?

```
node -v
```

**Comment by offirh** [comment]
both are v7.7.1

**Comment by polastre** [comment]
This version is going away, closing this issue as `wontfix`
